,target,doc
0,1,Modbus unavailable after timeout error from SyncWorker in HA Core 2021.7.1
1,1,### The problem
2,0,
3,1,"I have made the adjustment to the new configuration file setup for modbus. Everything functions again. I am using, sensors, switches and climates. "
4,0,
5,1,But after a while the modbus connection gets lost and I have to restart HA to get it to work again. 
6,0,
7,1,Have tried with different timeout and delay without any changes to the problem.
8,0,
9,1,### What is version of Home Assistant Core has the issue?
10,0,
11,1,core_2021.7.1
12,0,
13,1,### What was the last working version of Home Assistant Core?
14,0,
15,1,core_2021.6.6
16,0,
17,1,### What type of installation are you running?
18,0,
19,1,Home Assistant OS
20,0,
21,1,### Integration causing the issue
22,0,
23,1,Modbus
24,0,
25,1,### Link to integration documentation on our website
26,0,
27,1,_No response_
28,0,
29,1,### Example YAML snippet
30,0,
31,0,```yaml
32,0,modbus:
33,0,  - name: hub1
34,0,    type: tcp
35,0,    host: 10.10.10.25
36,0,    port: 502
37,0,    timeout: 4
38,0,    
39,0,    climates:
40,0,      - name: Heru FTX
41,0,        address: 1
42,0,        data_type: int
43,0,        input_type: holding
44,0,        target_temp_register: 1 
45,0,        count: 1
46,0,        temp_step: 1
47,0,        max_temp: 22
48,0,        min_temp: 15
49,0,    switches:
50,0,      - name: Ventilation Overpressure
51,0,        address: 1
52,0,        write_type: coil
53,0,      - name: Ventilation Boost
54,0,        address: 2
55,0,        write_type: coil
56,0,      - name: Ventilation Away
57,0,        address: 3
58,0,        write_type: coil
59,0,    sensors:
60,0,      - name: FTX Uteluft
61,0,        input_type: input
62,0,        address: 1
63,0,"        unit_of_measurement: ""°C"""
64,0,      - name: FTX Tilluft
65,0,        input_type: input
66,0,        address: 2
67,0,"        unit_of_measurement: ""°C"""
68,0,      - name: FTX Frånluft
69,0,        input_type: input
70,0,        address: 3
71,0,"        unit_of_measurement: ""°C"""
72,0,      - name: FTX Avluft
73,0,        input_type: input
74,0,        address: 4
75,0,"        unit_of_measurement: ""°C"""
76,0,      - name: FTX Rotor
77,0,        input_type: input
78,0,        address: 6
79,0,"        unit_of_measurement: ""°C"""
80,0,      - name: FTX Fläkt Tilluft
81,0,        input_type: input
82,0,        address: 24
83,0,        scan_interval: 5
84,0,"        unit_of_measurement: ""%"""
85,0,      - name: FTX Fläkt Frånluft
86,0,        input_type: input
87,0,        address: 25
88,0,        scan_interval: 5
89,0,"        unit_of_measurement: ""%"""
90,0,```
91,0,
92,0,
93,1,### Anything in the logs that might be useful for us?
94,0,
95,0,```txt
96,0,2021-07-09 17:51:48 DEBUG (SyncWorker_7) [pymodbus.client.sync] New Transaction state 'SENDING'
97,0,2021-07-09 17:51:53 DEBUG (SyncWorker_3) [pymodbus.client.sync] New Transaction state 'SENDING'
98,0,"2021-07-09 17:51:57 ERROR (SyncWorker_3) [homeassistant.components.modbus.modbus] Pymodbus: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)"
99,0,"2021-07-09 17:52:01 ERROR (SyncWorker_7) [pymodbus.client.sync] Connection to (10.10.10.25, 502) failed: timed out"
100,0,2021-07-09 17:52:01 DEBUG (SyncWorker_7) [homeassistant.components.modbus.modbus] Pymodbus: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(10.10.10.25:502)]
101,0,```
102,0,
103,0,
104,1,### Additional information
105,0,
106,1,I tried to go back to core_2021.6.6 and then of course it works as long as i revert back to the old config files. 
