,target,doc
0,1,RuntimeError: Overflow when unpacking long during training the model
1,1,"Hi I am training the model for custom dataset for QnA task. I have transformers version 4.0.0 and pytorch version 1.7.1. with the following code, I am getting the issue. "
2,0,```
3,0,trainer = Trainer(
4,0,"    model=model,                         # the instantiated ðŸ¤— Transformers model to be trained"
5,0,"    args=training_args,                  # training arguments, defined above"
6,0,"    train_dataset=train_dataset,         # training dataset"
7,0,          # evaluation dataset
8,0,)
9,0,trainer.train()
10,0,```
11,0,
12,1,Error is below:
13,0,
14,0,```
15,0,RuntimeError                              Traceback (most recent call last)
16,0,<ipython-input-16-3435b262f1ae> in <module>
17,0,----> 1 trainer.train()
18,0,
19,0,"~/.local/lib/python3.7/site-packages/transformers/trainer.py in train(self, model_path, trial)"
20,0,"    727             self.control = self.callback_handler.on_epoch_begin(self.args, self.state, self.control)"
21,0,    728 
22,0,"--> 729             for step, inputs in enumerate(epoch_iterator):"
23,0,    730 
24,0,    731                 # Skip past any already trained steps if resuming training
25,0,
26,0,~/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
27,0,    433         if self._sampler_iter is None:
28,0,    434             self._reset()
29,0,--> 435         data = self._next_data()
30,0,    436         self._num_yielded += 1
31,0,    437         if self._dataset_kind == _DatasetKind.Iterable and \
32,0,
33,0,~/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py in _next_data(self)
34,0,    473     def _next_data(self):
35,0,    474         index = self._next_index()  # may raise StopIteration
36,0,--> 475         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
37,0,    476         if self._pin_memory:
38,0,    477             data = _utils.pin_memory.pin_memory(data)
39,0,
40,0,"~/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)"
41,0,"     42     def fetch(self, possibly_batched_index):"
42,0,     43         if self.auto_collation:
43,0,---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
44,0,     45         else:
45,0,     46             data = self.dataset[possibly_batched_index]
46,0,
47,0,~/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
48,0,"     42     def fetch(self, possibly_batched_index):"
49,0,     43         if self.auto_collation:
50,0,---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
51,0,     45         else:
52,0,     46             data = self.dataset[possibly_batched_index]
53,0,
54,0,"<ipython-input-7-80744e22dabe> in __getitem__(self, idx)"
55,0,      6 
56,0,"      7     def __getitem__(self, idx):"
57,0,"----> 8         return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}"
58,0,      9 
59,0,     10     def __len__(self):
60,0,
61,0,<ipython-input-7-80744e22dabe> in <dictcomp>(.0)
62,0,      6 
63,0,"      7     def __getitem__(self, idx):"
64,0,"----> 8         return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}"
65,0,      9 
66,0,     10     def __len__(self):
67,0,
68,0,RuntimeError: Overflow when unpacking long
69,0,```
